// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sfyuwnlmwgbtgnfmvaoj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNmeXV3bmxtd2didGduZm12YW9qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMjI0MzcsImV4cCI6MjA2Mzg5ODQzN30.8JYbKaW4jLOs-BjgybiggNfS4ejOhRAJjshwOF15wWc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);